global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'csv_exporter'
    static_configs:
      - targets: ['csv_exporter:8000']